### PR TITLE
Fixes UTF-8-BOM XML parsing

### PR DESCRIPTION
**Pull request by cbabos**
I've added strip-bom to parseString method, because in my case a podcast XML contained BOM character and the node-xml-lite crashed on it. 
My problem was with a podcast XML: http://feeds.podtrac.com/kJVKNvGiQn6Q

Notice: I've only added this to the parseString method, so it will continue to crash with other sources!

Notice2: Sorry for the mess with test/ but instead of writing an eye-verified test, I wanted to use mocha and assertjs for testing the removal of the BOM. 
I've preserved your original test file in test/original-test/test.js
I hope it's ok for you.

### CODE REVIEW

**Comment by cbabos** [comment]
Sorry for the mess with test/ but instead of writing an eye-verified test, I wanted to use mocha and assertjs for testing the removal of the BOM. 
I've preserved your original test file in test/original-test/test.js
I hope it's ok for you.

**Comment by cbabos** [comment]
@hgourvest Hello there, is there any problem with my pull? If there is please notify me, so I can fix it.

**Comment by hgourvest** [comment]
I think it should be implemented in the parser itself, and should not require the stripbom module, only ut8 bom should supported.

**Comment by cbabos** [comment]
What would be the next step? I think the options are: 
- implementing the existing code from strip-bom (if you really want to reinvent the wheel)
- use this pull request
- leave it as is, and the libraries that are using node-xml-lite should implement BOM-stripping? 

In my opinion, the best approach would be to use strip-bom, or equivalent, because I think that one tool should do one thing, and node-xml-lite has a task to parse xml-s, not stripping BOM-s, but of course: it's your library, so it's really just an opinion.

**Comment by hgourvest** [comment]
I understand you defend your code, but you know, detecting 3 chars in a parser is not reinventing the wheel, it is just more efficient than using a third party module that do more than we need, and it will works for all parsing functions. I would like to keep it "lite"

**Comment by cbabos** [comment]
Okay then, I'll implement (if you'll want it by me) it of course. It's not about my code, just didn't understood why would you leave out the a library like this.

**Comment by hgourvest** [comment]
good, do it, I will check and fix it if needed. Thanks

**Comment by cbabos** [comment]
Also I'll rewrite the tests using mocha, so the whole project will be tested (actually maybe there will be some missing tests, so if you want you can complete them). I hope I can finish it today, but maybe there will be a little waiting before the updated pull.

**Comment by cbabos** [comment]
I've updated the code. The implementation uses the main codebase from the strip-bom. I don't think there is a better solution for the problem. 
Also I wrote the necessary tests to ensure that parseFile, parseFileSync, parseBuffer and parseString methods are dealing equally with XML parsing and with BOM. 
The solution by myself isn't the best I think, but I couldn't come up with a better version.

**Comment by hgourvest** [comment]
Thanks for trying, I finally did it myself, take a look on the last commit.

**Comment by cbabos** [comment]
Okay, I've runned my tests on your version, it's working fine. Closing.

**Comment by hgourvest** [comment]
ok, just published the newest version on npm

**Pull request closed without merging**
